---
- name: Manage Apache on web servers
  hosts: all
  remote_user: root

  tasks:
    - name: Ensure Apache is at the latest version
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: Ensure Apache is started and enabled
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: yes
