---
- name: Manage Apache on web servers
  hosts: all
  remote_user: root

 - name: Ensure Apache is started and enabled
  ansible.builtin.systemd:
    name: httpd
    state: started
    enabled: yes

        
    
