---
- name: Install and enable Apache on web servers
  hosts: all
  become: yes  # Ensures tasks run with elevated privileges

  tasks:
    - name: Ensure Apache is installed at the latest version
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: Ensure Apache is started and enabled
      ansible.builtin.systemd:
        name: httpd
        state: started
  
